"""user seat limit; game and report ownership index

Revision ID: 767c824c2fcb
Revises: f064316a6b34
Created: 2026-09-20 10:50:11.299983
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '767c824c2fcb'
down_revision: Union[str, None] = 'f064316a6b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default is required, not cosmetic: adding a NOT NULL column to a table that already
    # has rows fails without one. Autogenerate does not add it. It is dropped again afterwards so
    # the column matches the model, where the default is applied in Python.
    """Add the per-account seat limit and the game and report ownership columns."""
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_seats_per_game', sa.Integer(), nullable=False,
                                      server_default='0'))
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('max_seats_per_game', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """Remove them again."""
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('max_seats_per_game')

    # ### end Alembic commands ###
