"""initial schema: accounts, servers, sharing

Revision ID: f064316a6b34
Revises: 
Created: 2026-09-20 09:39:58.802893
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f064316a6b34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """Create the initial schema: accounts, sessions, invitations, servers, sharing and audit."""
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=40), nullable=True),
    sa.Column('actor_label', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=24), nullable=True),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('rate_limits',
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('settings_kv',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('handle', sa.String(length=40), nullable=False),
    sa.Column('handle_lower', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_lower', sa.String(length=320), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tz', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('data_sharing', sa.String(length=16), nullable=False),
    sa.Column('caps', sa.JSON(), nullable=False),
    sa.Column('invite_quota', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_games', sa.Integer(), nullable=False),
    sa.Column('is_local_owner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_by', sa.String(length=40), nullable=True),
    sa.Column('suspended_reason', sa.Text(), nullable=True),
    sa.Column('invited_by', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email_lower'), ['email_lower'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_handle_lower'), ['handle_lower'], unique=True)

    op.create_table('acl_entries',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('object_type', sa.String(length=24), nullable=False),
    sa.Column('object_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('permission', sa.String(length=16), nullable=False),
    sa.Column('granted_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_type', 'object_id', 'user_id', 'permission', name='uq_acl_subject_permission')
    )
    with op.batch_alter_table('acl_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acl_entries_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_acl_entries_object_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_acl_entries_user_id'), ['user_id'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('email_tokens',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('new_email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('games',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('owner_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('slug', sa.String(length=48), nullable=False),
    sa.Column('data_sharing', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('save_path', sa.String(length=512), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_slug'), ['slug'], unique=True)

    op.create_table('identities',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_identity_provider_subject')
    )
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identities_user_id'), ['user_id'], unique=False)

    op.create_table('invites',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('skip_probation', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invites_code'), ['code'], unique=True)

    op.create_table('reports',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('owner_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('slug', sa.String(length=48), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_slug'), ['slug'], unique=True)

    op.create_table('server_groups',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('owner_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('slug', sa.String(length=48), nullable=False),
    sa.Column('accepts_requests', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('server_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_server_groups_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_server_groups_slug'), ['slug'], unique=True)

    op.create_table('access_grants',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('group_id', sa.String(length=40), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_user_id', sa.String(length=40), nullable=True),
    sa.Column('purposes', sa.JSON(), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['server_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_grants_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_grants_subject_user_id'), ['subject_user_id'], unique=False)

    op.create_table('servers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('owner_id', sa.String(length=40), nullable=False),
    sa.Column('group_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('reach', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_concurrent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['server_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servers_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_servers_owner_id'), ['owner_id'], unique=False)

    op.create_table('availability_windows',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('grant_id', sa.String(length=40), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_min', sa.Integer(), nullable=False),
    sa.Column('end_min', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['access_grants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_windows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_windows_grant_id'), ['grant_id'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('grant_id', sa.String(length=40), nullable=False),
    sa.Column('period', sa.String(length=12), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('behavior', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['access_grants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_grant_id'), ['grant_id'], unique=False)

    op.create_table('worker_tokens',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('server_id', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ip', sa.String(length=64), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_tokens_server_id'), ['server_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_tokens_token_hash'), ['token_hash'], unique=True)

    op.create_table('budget_entries',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('budget_id', sa.String(length=40), nullable=False),
    sa.Column('activity_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('reserved', sa.Float(), nullable=False),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('period_key', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_entries_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_entries_budget_id'), ['budget_id'], unique=False)
        batch_op.create_index('ix_budget_entries_budget_period', ['budget_id', 'period_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_entries_period_key'), ['period_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """Drop everything this migration created."""
    with op.batch_alter_table('budget_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_entries_period_key'))
        batch_op.drop_index('ix_budget_entries_budget_period')
        batch_op.drop_index(batch_op.f('ix_budget_entries_budget_id'))
        batch_op.drop_index(batch_op.f('ix_budget_entries_activity_id'))

    op.drop_table('budget_entries')
    with op.batch_alter_table('worker_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_worker_tokens_server_id'))

    op.drop_table('worker_tokens')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_grant_id'))

    op.drop_table('budgets')
    with op.batch_alter_table('availability_windows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_windows_grant_id'))

    op.drop_table('availability_windows')
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_owner_id'))
        batch_op.drop_index(batch_op.f('ix_servers_group_id'))

    op.drop_table('servers')
    with op.batch_alter_table('access_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_grants_subject_user_id'))
        batch_op.drop_index(batch_op.f('ix_access_grants_group_id'))

    op.drop_table('access_grants')
    with op.batch_alter_table('server_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_server_groups_slug'))
        batch_op.drop_index(batch_op.f('ix_server_groups_owner_id'))

    op.drop_table('server_groups')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_slug'))
        batch_op.drop_index(batch_op.f('ix_reports_owner_id'))

    op.drop_table('reports')
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invites_code'))

    op.drop_table('invites')
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identities_user_id'))

    op.drop_table('identities')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_slug'))
        batch_op.drop_index(batch_op.f('ix_games_owner_id'))

    op.drop_table('games')
    with op.batch_alter_table('email_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_tokens_token_hash'))

    op.drop_table('email_tokens')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token_hash'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('acl_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acl_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_acl_entries_object_type'))
        batch_op.drop_index(batch_op.f('ix_acl_entries_object_id'))

    op.drop_table('acl_entries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_handle_lower'))
        batch_op.drop_index(batch_op.f('ix_users_email_lower'))

    op.drop_table('users')
    op.drop_table('settings_kv')
    op.drop_table('rate_limits')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
