//! GENERATED by `cargo xtask gen-params` from `params/basic-1.json` (DESIGN.md P2.3.2): one field
//! per parameter, `serde(deny_unknown_fields)`, no defaults.
//!
//! A placeholder until package 2-01a writes the generator (`xtask/src/gen_params.rs`) and
//! `cargo xtask check` starts holding this file to it: package 2-00a had no schema to generate
//! from (2-00b writes it).

/// The effective parameters of a `basic-1` spec: the schema's defaults overlaid with its
/// overrides.
#[derive(Clone, Debug, Default, PartialEq)]
#[non_exhaustive]
pub struct Params {}
