//! A version's parameters (DESIGN.md P2.3.2; `PARAM_GROUPS` and `DEFAULT_PARAMS`,
//! basic.py:32-628): one JSON schema per version, the Bots page's, `profiles.py`'s and the bot's,
//! generated into a struct.
//!
//! - `schema.rs`: the schemas, verbatim (`params/<version>.json`, from package 2-00b), and the
//!   types its parameters are described with ([`Spec`]);
//! - `gen.rs`: GENERATED by `cargo xtask gen-params` from the schema: [`Params`], one field per
//!   key, an enum per choice, and [`SPECS`], every parameter as data;
//! - `clean.rs`: `profiles.clean_params` (profiles.py:185-225), with its two laxities fixed;
//! - `resolve.rs`: [`Resolved`], the names of a [`Params`] turned into a ruleset's ids.
//!
//! [`Tuning`] holds a spec's cleaned [`Overrides`], the effective [`Params`] (the schema's
//! defaults overlaid with them), the engine's [`AdvisorParams`] read from the same map, and the
//! resolution against each ruleset the spec has met, so that every spec with the same
//! parameters shares one cache however often hosts rebuild their bots.

pub(crate) mod clean;
// `gen` is a reserved word from edition 2024; the file keeps the name the design gives it. It is
// written by a generator and held to it by `cargo xtask check`, not by rustfmt.
#[rustfmt::skip]
#[path = "gen.rs"]
mod generated;
pub(crate) mod resolve;
pub(crate) mod schema;

use std::collections::BTreeMap;
use std::sync::{Arc, Mutex, OnceLock, PoisonError};

use citar_engine::game::advisor::AdvisorParams;
use citar_engine::rules::{Ruleset, RulesetId};
use serde::de::{self, Deserializer, SeqAccess, Visitor};
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};
use smallvec::SmallVec;

pub use self::generated::*;
pub use self::resolve::Resolved;
pub use self::schema::{Fixed, Kind, Spec};
use crate::versions::VersionId;

/// The parameter `key` of `basic-1`.
#[must_use]
pub fn spec(key: &str) -> Option<&'static Spec> {
    let i = BY_KEY.binary_search_by(|(k, _)| (*k).cmp(key)).ok()?;
    SPECS.get(usize::from(BY_KEY[i].1))
}

/// `basic-1`'s defaults as a map, in the schema's order (`DEFAULT_PARAMS`).
#[must_use]
pub fn defaults() -> Map<String, Value> {
    SPECS.iter().map(|s| (s.key.to_owned(), s.default.to_json())).collect()
}

/// The names of an order or a list (DESIGN.md P2.3.2): the parameter's default, one of its
/// presets, or names of its own.
///
/// `null` and `"default"` both read as [`Default`](Self::Default): the order the parameter's
/// `default` preset gives, or, for a parameter without one, its default names. (Python's
/// `POLICY_ORDERS["default"]` was `None` and fell back to the built-in order the schema now
/// names `default`; a list without presets would have iterated the letters of `"default"`.)
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum NameList {
    Default,
    /// A preset's name, which `clean()` checked the parameter has.
    Preset(Box<str>),
    Names(Vec<Box<str>>),
}

impl<'de> Deserialize<'de> for NameList {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        struct NamesVisitor;

        impl<'de> Visitor<'de> for NamesVisitor {
            type Value = NameList;

            fn expecting(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str("null, \"default\", a preset's name or a list of names")
            }

            fn visit_unit<E: de::Error>(self) -> Result<NameList, E> {
                Ok(NameList::Default)
            }

            fn visit_none<E: de::Error>(self) -> Result<NameList, E> {
                Ok(NameList::Default)
            }

            fn visit_str<E: de::Error>(self, s: &str) -> Result<NameList, E> {
                Ok(if s == "default" { NameList::Default } else { NameList::Preset(s.into()) })
            }

            fn visit_seq<A: SeqAccess<'de>>(self, mut seq: A) -> Result<NameList, A::Error> {
                let mut names = Vec::with_capacity(seq.size_hint().unwrap_or_default());
                while let Some(n) = seq.next_element::<Box<str>>()? {
                    names.push(n);
                }
                Ok(NameList::Names(names))
            }
        }

        d.deserialize_any(NamesVisitor)
    }
}

/// Overrides that do not clean, with `clean_params`' message where Python had one.
#[derive(Clone, Debug, PartialEq, Eq, thiserror::Error)]
#[error("{message}")]
pub struct ParamError {
    /// The parameter it is about, if one.
    pub key: Option<String>,
    pub message: String,
}

impl ParamError {
    /// An error about `key`, or about the whole when `None`.
    #[must_use]
    pub fn new(key: Option<&str>, message: impl Into<String>) -> Self {
        Self { key: key.map(str::to_owned), message: message.into() }
    }
}

/// Cleaned overrides: keys known to the version's schema, values of their parameter's type and
/// unlike its default, in key order. Only [`crate::clean`] makes non-empty ones, so every
/// [`Tuning`] built from them reads.
#[derive(Clone, Debug, Default, PartialEq, Serialize)]
#[serde(transparent)]
pub struct Overrides(BTreeMap<String, Value>);

impl Overrides {
    /// Wraps overrides that [`crate::clean`] has cleaned.
    #[must_use]
    pub(crate) const fn cleaned(map: BTreeMap<String, Value>) -> Self {
        Self(map)
    }

    /// The override of `key`, if any.
    #[must_use]
    pub fn get(&self, key: &str) -> Option<&Value> {
        self.0.get(key)
    }

    /// Every override, in key order.
    pub fn iter(&self) -> impl Iterator<Item = (&str, &Value)> + '_ {
        self.0.iter().map(|(k, v)| (k.as_str(), v))
    }

    /// How many there are.
    #[must_use]
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Whether there are none.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// The overrides as a JSON object, in key order.
    #[must_use]
    pub fn to_json(&self) -> Value {
        self.0.iter().map(|(k, v)| (k.clone(), v.clone())).collect()
    }

    /// The canonical text the fingerprint hashes: compact JSON, keys sorted.
    #[must_use]
    pub fn canonical(&self) -> String {
        // A map of strings to JSON values always serialises.
        serde_json::to_string(&self.0).unwrap_or_default()
    }

    /// The schema's defaults with these overlaid: the effective parameters as a map, in the
    /// schema's order (`effective_params`).
    #[must_use]
    pub fn effective(&self) -> Map<String, Value> {
        let mut map = defaults();
        for (k, v) in &self.0 {
            map.insert(k.clone(), v.clone());
        }
        map
    }
}

/// The resolutions a [`Tuning`] has made, one per ruleset met (almost always one).
type ResolvedCache = SmallVec<[(RulesetId, Arc<Resolved>); 1]>;

/// `basic-1`'s parameters at their defaults, and the advisor's read from the same map, built
/// once.
///
/// The generated [`Params::schema_defaults`] cannot fail, and tests hold it equal to the
/// defaults map deserialized, and the advisor's parameters from that map equal to
/// `AdvisorParams::default()` (Python's, field by field, 1c-07); so the fallback to the
/// advisor's own defaults is never taken while the tests pass.
fn default_params() -> &'static (Params, AdvisorParams) {
    static DEFAULTS: OnceLock<(Params, AdvisorParams)> = OnceLock::new();
    DEFAULTS.get_or_init(|| {
        let advisor =
            AdvisorParams::from_map(&Value::Object(defaults()), crate::BotSpec::DEFAULT_AGGRESSION);
        debug_assert!(advisor.is_ok(), "the advisor reads basic-1's defaults: {advisor:?}");
        (Params::schema_defaults(), advisor.unwrap_or_default())
    })
}

/// A spec's parameters: its cleaned overrides, the effective [`Params`], the advisor's
/// parameters from the same map, and the resolution of their names against each ruleset met
/// (DESIGN.md P2.3.1). Shared through an `Arc` by every spec with the same overrides.
#[derive(Debug)]
pub struct Tuning {
    version: VersionId,
    overrides: Overrides,
    params: Params,
    advisor: AdvisorParams,
    resolved: Mutex<ResolvedCache>,
}

impl Tuning {
    /// The tuning of `version` with `overrides` (which [`crate::clean`] made for it): the
    /// schema's defaults overlaid with them. `idle` takes no parameters, so its tuning is
    /// `basic-1`'s defaults, which it never reads.
    #[must_use]
    pub fn new(version: VersionId, overrides: Overrides) -> Self {
        let (params, advisor) = match version {
            VersionId::Idle => default_params().clone(),
            VersionId::Basic1 if overrides.is_empty() => default_params().clone(),
            VersionId::Basic1 => {
                let map = Value::Object(overrides.effective());
                // clean() typed every value as its field reads it (an int inside i32, a float
                // finite, a choice among its names), which its tests hold for every kind; were one
                // ever unreadable, the defaults play rather than a half-read tuning.
                let params = Params::deserialize(&map);
                let advisor = AdvisorParams::from_map(&map, crate::BotSpec::DEFAULT_AGGRESSION);
                debug_assert!(params.is_ok() && advisor.is_ok(), "clean()'s output must read");
                match (params, advisor) {
                    (Ok(p), Ok(a)) => (p, a),
                    _ => default_params().clone(),
                }
            }
        };
        let overrides = if version == VersionId::Idle { Overrides::default() } else { overrides };
        Self { version, overrides, params, advisor, resolved: Mutex::default() }
    }

    /// The version these parameters are for.
    #[must_use]
    pub const fn version(&self) -> VersionId {
        self.version
    }

    /// The cleaned overrides.
    #[must_use]
    pub const fn overrides(&self) -> &Overrides {
        &self.overrides
    }

    /// The effective parameters.
    #[must_use]
    pub const fn params(&self) -> &Params {
        &self.params
    }

    /// The production advisor's parameters, read from the same effective map, with
    /// `aggression` (the seat's, which a spec holds and the tuning does not).
    #[must_use]
    pub fn advisor(&self, aggression: f64) -> AdvisorParams {
        AdvisorParams { aggression, ..self.advisor.clone() }
    }

    /// The parameters resolved against `rules`, computed once per ruleset and kept.
    pub fn resolved(&self, rules: &'static Ruleset) -> Arc<Resolved> {
        let id = rules.id();
        // A panic elsewhere while the lock was held leaves a cache that is still whole: every
        // entry is pushed complete.
        let mut cache = self.resolved.lock().unwrap_or_else(PoisonError::into_inner);
        if let Some((_, r)) = cache.iter().find(|(rid, _)| *rid == id) {
            return Arc::clone(r);
        }
        let r = Arc::new(Resolved::new(&self.params, rules));
        cache.push((id, Arc::clone(&r)));
        r
    }
}
