//! A version's parameters (DESIGN.md P2.3.2): one JSON schema per version, the Bots page's,
//! `profiles.py`'s and the bot's, generated into a struct.
//!
//! - `schema.rs`: the schemas, verbatim (`params/<version>.json`, from package 2-00b);
//! - `gen.rs`: GENERATED by `cargo xtask gen-params` from the schema: [`Params`], one field per
//!   key (package 2-01a; a placeholder until then);
//! - `clean.rs`: `profiles.clean_params`, with its two laxities fixed;
//! - `resolve.rs`: [`Resolved`], the names of a [`Params`] turned into a ruleset's ids.
//!
//! [`Tuning`] holds a spec's cleaned [`Overrides`], the effective [`Params`] (the schema's
//! defaults overlaid with them), and the resolution against each ruleset the spec has met, so
//! that every spec with the same parameters shares one cache however often hosts rebuild their
//! bots.

pub(crate) mod clean;
// `gen` is a reserved word from edition 2024; the file keeps the name the design gives it.
#[path = "gen.rs"]
mod generated;
mod resolve;
pub(crate) mod schema;

use std::collections::BTreeMap;
use std::sync::{Arc, Mutex, PoisonError};

use citar_engine::rules::{Ruleset, RulesetId};
use serde::Serialize;
use serde_json::Value;
use smallvec::SmallVec;

pub use self::generated::Params;
pub use self::resolve::Resolved;
use crate::versions::VersionId;

/// Overrides that do not clean, with `clean_params`' message where Python had one.
#[derive(Clone, Debug, PartialEq, Eq, thiserror::Error)]
#[error("{message}")]
pub struct ParamError {
    /// The parameter it is about, if one.
    pub key: Option<String>,
    pub message: String,
}

impl ParamError {
    /// An error about `key`, or about the whole when `None`.
    #[must_use]
    pub fn new(key: Option<&str>, message: impl Into<String>) -> Self {
        Self { key: key.map(str::to_owned), message: message.into() }
    }
}

/// Cleaned overrides: keys known to the version's schema, values of their parameter's type and
/// unlike its default, in key order. Only [`crate::clean`] makes non-empty ones.
#[derive(Clone, Debug, Default, PartialEq, Serialize)]
#[serde(transparent)]
pub struct Overrides(BTreeMap<String, Value>);

impl Overrides {
    /// Wraps overrides that [`crate::clean`] has cleaned.
    #[must_use]
    pub(crate) const fn cleaned(map: BTreeMap<String, Value>) -> Self {
        Self(map)
    }

    /// The override of `key`, if any.
    #[must_use]
    pub fn get(&self, key: &str) -> Option<&Value> {
        self.0.get(key)
    }

    /// Every override, in key order.
    pub fn iter(&self) -> impl Iterator<Item = (&str, &Value)> + '_ {
        self.0.iter().map(|(k, v)| (k.as_str(), v))
    }

    /// How many there are.
    #[must_use]
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Whether there are none.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// The overrides as a JSON object, in key order.
    #[must_use]
    pub fn to_json(&self) -> Value {
        self.0.iter().map(|(k, v)| (k.clone(), v.clone())).collect()
    }

    /// The canonical text the fingerprint hashes: compact JSON, keys sorted.
    #[must_use]
    pub fn canonical(&self) -> String {
        // A map of strings to JSON values always serialises.
        serde_json::to_string(&self.0).unwrap_or_default()
    }
}

/// The resolutions a [`Tuning`] has made, one per ruleset met (almost always one).
type ResolvedCache = SmallVec<[(RulesetId, Arc<Resolved>); 1]>;

/// A spec's parameters: its cleaned overrides, the effective [`Params`], and the resolution of
/// their names against each ruleset met (DESIGN.md P2.3.1). Shared through an `Arc` by every
/// spec with the same overrides.
#[derive(Debug)]
pub struct Tuning {
    overrides: Overrides,
    params: Params,
    resolved: Mutex<ResolvedCache>,
}

impl Tuning {
    /// The tuning of `version` with `overrides`: the schema's defaults overlaid with them.
    ///
    /// The stub of package 2-00a has no schema to read and gives the placeholder [`Params`];
    /// 2-01a deserializes the effective map.
    #[must_use]
    pub fn new(version: VersionId, overrides: Overrides) -> Self {
        let _ = version;
        Self { overrides, params: Params::default(), resolved: Mutex::default() }
    }

    /// The cleaned overrides.
    #[must_use]
    pub const fn overrides(&self) -> &Overrides {
        &self.overrides
    }

    /// The effective parameters.
    #[must_use]
    pub const fn params(&self) -> &Params {
        &self.params
    }

    /// The parameters resolved against `rules`, computed once per ruleset and kept.
    pub fn resolved(&self, rules: &'static Ruleset) -> Arc<Resolved> {
        let id = rules.id();
        // A panic elsewhere while the lock was held leaves a cache that is still whole: every
        // entry is pushed complete.
        let mut cache = self.resolved.lock().unwrap_or_else(PoisonError::into_inner);
        if let Some((_, r)) = cache.iter().find(|(rid, _)| *rid == id) {
            return Arc::clone(r);
        }
        let r = Arc::new(Resolved::new(&self.params, rules));
        cache.push((id, Arc::clone(&r)));
        r
    }
}
