"""Generate UnCiv's unique types (name, placeholder, signature) from UnCiv's UniqueType.kt.

    python scripts/gen_unique_types.py <Unciv checkout>          writes citar/engine/unique_types.py
    python scripts/gen_unique_types.py --tsv <Unciv checkout>    writes crates/citar-engine/unique_types.tsv

The TSV is what the Rust engine reads (`cargo xtask gen-uniques`, crates/citar-engine/DESIGN.md 5.4).
"""
import re
import sys
from pathlib import Path

args = [a for a in sys.argv[1:] if a != "--tsv"]
TSV = "--tsv" in sys.argv[1:]
if len(args) != 1:
    sys.exit("usage: python scripts/gen_unique_types.py [--tsv] <path to an Unciv checkout>\n"
             "       git clone --depth 1 https://github.com/yairm210/Unciv")
UNCIV = Path(args[0])
SRC = UNCIV / "core/src/com/unciv/models/ruleset/unique/UniqueType.kt"
REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "citar" / "engine" / "unique_types.py"
OUT_TSV = REPO / "crates" / "citar-engine" / "unique_types.tsv"
TSV_HEADER = """\
# UnCiv's unique types: each type's name, its placeholder, and UnCiv's text with the kind of each
# parameter. From UnCiv's UniqueType.kt (https://github.com/yairm210/Unciv), MPL-2.0, like CITAR.
# Converted once from citar/engine/unique_types.py; `python scripts/gen_unique_types.py --tsv
# <Unciv checkout>` refreshes it from UniqueType.kt. `cargo xtask gen-uniques` reads it, with
# unique_supported.toml, to write src/unique/gen.rs (crates/citar-engine/DESIGN.md 5.4).
# Columns, tab-separated: name, placeholder, signature. The order is UnCiv's.
"""

src = SRC.read_text(encoding="utf-8")
consts_src = (UNCIV / "core/src/com/unciv/Constants.kt").read_text(encoding="utf-8")
CONSTS = dict(re.findall(r'const val (\w+) = "([^"]*)"', consts_src))
# entries whose text is a Constants reference, e.g. FreshWater(Constants.freshWater, ...)
src = re.sub(r'(\(\s*)Constants\.(\w+)', lambda m: f'{m.group(1)}"{CONSTS.get(m.group(2), m.group(2))}"', src)
body = src[src.index("enum class UniqueType"):]
pat = re.compile(r'^\s{4}([A-Z][A-Za-z0-9]+)\("((?:[^"\\]|\\.)*)"', re.M)
seen, rows = set(), []
for m in pat.finditer(body):
    name, text = m.group(1), m.group(2).replace('\\"', '"')
    if name in seen:
        continue
    seen.add(name)
    ph, depth = [], 0
    for c in text:
        if c == "[":
            if depth == 0:
                ph.append("[]")
            depth += 1
            continue
        if c == "]":
            depth -= 1
            continue
        if depth == 0:
            ph.append(c)
    rows.append((name, "".join(ph), text))

if TSV:
    lines = [TSV_HEADER.rstrip("\n")] + [f"{n}\t{p}\t{t}" for n, p, t in rows]
    OUT_TSV.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(len(rows), "unique types ->", OUT_TSV)
    sys.exit(0)

lines = ['"""UnCiv UniqueType names -> placeholder text. Generated by scripts/gen_unique_types.py from UnCiv\'s',
         'UniqueType.kt (MPL-2.0). Do not edit by hand."""', ""]
for n, p, t in rows:
    lines.append(f"{n} = {p!r}  # {t}")
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(len(rows), "unique types ->", OUT)
