"""Generate citar/engine/unique_types.py (UnCiv UniqueType name -> placeholder text) from UnCiv's UniqueType.kt."""
import re
import sys
from pathlib import Path

if len(sys.argv) < 2:
    sys.exit("usage: python scripts/gen_unique_types.py <path to an Unciv checkout>\n"
             "       git clone --depth 1 https://github.com/yairm210/Unciv")
UNCIV = Path(sys.argv[1])
SRC = UNCIV / "core/src/com/unciv/models/ruleset/unique/UniqueType.kt"
OUT = Path(__file__).resolve().parent.parent / "citar" / "engine" / "unique_types.py"

src = SRC.read_text(encoding="utf-8")
consts_src = (UNCIV / "core/src/com/unciv/Constants.kt").read_text(encoding="utf-8")
CONSTS = dict(re.findall(r'const val (\w+) = "([^"]*)"', consts_src))
# entries whose text is a Constants reference, e.g. FreshWater(Constants.freshWater, ...)
src = re.sub(r'(\(\s*)Constants\.(\w+)', lambda m: f'{m.group(1)}"{CONSTS.get(m.group(2), m.group(2))}"', src)
body = src[src.index("enum class UniqueType"):]
pat = re.compile(r'^\s{4}([A-Z][A-Za-z0-9]+)\("((?:[^"\\]|\\.)*)"', re.M)
seen, rows = set(), []
for m in pat.finditer(body):
    name, text = m.group(1), m.group(2).replace('\\"', '"')
    if name in seen:
        continue
    seen.add(name)
    ph, depth = [], 0
    for c in text:
        if c == "[":
            if depth == 0:
                ph.append("[]")
            depth += 1
            continue
        if c == "]":
            depth -= 1
            continue
        if depth == 0:
            ph.append(c)
    rows.append((name, "".join(ph), text))

lines = ['"""UnCiv UniqueType names -> placeholder text. Generated by scripts/gen_unique_types.py from UnCiv\'s',
         'UniqueType.kt (MPL-2.0). Do not edit by hand."""', ""]
for n, p, t in rows:
    lines.append(f"{n} = {p!r}  # {t}")
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(len(rows), "unique types ->", OUT)
