"""Regenerate requirements.txt from pyproject.toml.

The deployment installs with ``pip install -r requirements.txt`` rather than installing the package,
because the service runs the code in place from ``/opt/citar``. That leaves two lists of
dependencies that can disagree, and the way they disagree is a deployment that starts and then
fails on an import nobody tested.

So the file is generated. ``pyproject.toml`` is the source of truth; this writes the ``server``
extra out in a form pip can read, with a header saying not to edit it.

    python scripts/sync_requirements.py           # write it
    python scripts/sync_requirements.py --check    # non-zero exit if it is out of date (for CI)
"""
from __future__ import annotations

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
#: The extras a deployment needs. Local-model client libraries are deliberately absent: a server
#: reaches models through workers and the Anthropic API, and does not run them itself.
EXTRAS = ("anthropic", "oauth", "keyring", "worker")


def render() -> str:
    data = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    project = data["project"]
    optional = project["optional-dependencies"]

    lines = [
        "# Generated by scripts/sync_requirements.py from pyproject.toml. Do not edit.",
        "#",
        "# What a CITAR server installs. The project itself is not installed as a package on the",
        "# server: the service runs the code in place from /opt/citar, so only its dependencies are",
        "# needed here. For a workstation, `pip install citar[all]` instead.",
        "",
        "# Core",
    ]
    lines += sorted(project["dependencies"])

    for extra in EXTRAS:
        entries = [d for d in optional[extra] if not d.startswith("citar[")]
        if not entries:
            continue
        lines += ["", f"# {extra}"]
        lines += sorted(entries)

    lines += [
        "",
        "# Optional: only when CITAR_DB_URL points at PostgreSQL.",
        "# " + optional["postgres"][0],
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    path = ROOT / "requirements.txt"
    wanted = render()
    if "--check" in sys.argv:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current.replace("\r\n", "\n") != wanted:
            print("requirements.txt is out of date with pyproject.toml.")
            print("Run: python scripts/sync_requirements.py")
            return 1
        print("requirements.txt matches pyproject.toml.")
        return 0
    path.write_text(wanted, encoding="utf-8", newline="\n")
    print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
